"""Dashboard operationalization exports for expectation failure subsystem."""

from .dashboard_o1_export_schema import (
    build_dashboard_alert_facts,
    build_dashboard_benchmark_facts,
    build_dashboard_entity_facts,
    build_dashboard_evidence_facts,
    build_dashboard_export_manifest,
    build_dashboard_o1_export_payload,
    build_dashboard_replay_facts,
    build_dashboard_report_metadata,
    build_dashboard_subsector_facts,
)

__all__ = [
    "build_dashboard_entity_facts",
    "build_dashboard_subsector_facts",
    "build_dashboard_alert_facts",
    "build_dashboard_replay_facts",
    "build_dashboard_benchmark_facts",
    "build_dashboard_evidence_facts",
    "build_dashboard_report_metadata",
    "build_dashboard_export_manifest",
    "build_dashboard_o1_export_payload",
    "build_dashboard_o2_table_contracts",
    "build_dashboard_o2_unique_key_contracts",
    "build_dashboard_o2_column_contracts",
    "build_dashboard_o2_upsert_payload",
    "validate_dashboard_o2_payload",
    "build_dashboard_o2_persistence_manifest",
    "build_dashboard_o2_contract_report",
    "build_dashboard_o3_write_plan",
    "validate_dashboard_o3_write_plan",
    "execute_dashboard_o3_write_plan",
    "build_dashboard_o3_write_result_manifest",
    "build_dashboard_o3_dry_run_report",
    "build_dashboard_o3_persistence_audit_report",
    "build_dashboard_o4_view_model",
    "build_dashboard_o4_page_registry",
    "build_dashboard_o4_filter_options",
    "build_dashboard_o4_kpi_cards",
    "build_dashboard_o4_entity_table",
    "build_dashboard_o4_subsector_table",
    "build_dashboard_o4_alert_table",
    "build_dashboard_o4_benchmark_table",
    "build_dashboard_o4_replay_table",
    "build_dashboard_o4_evidence_table",
    "build_dashboard_o4_certification_panel",
    "validate_dashboard_o4_view_model",
    "build_dashboard_o4_ui_manifest",
    "build_dashboard_o5_certification_gates",
    "run_dashboard_o5_operationalization_certification",
    "build_dashboard_o5_api_inventory",
    "build_dashboard_o5_artifact_inventory",
    "build_dashboard_o5_boundary_certification",
    "build_dashboard_o5_test_coverage_summary",
    "build_dashboard_o5_closeout_report",
    "build_dashboard_o6_read_adapter_report_payload",
    "build_dashboard_supabase_snapshot",
    "load_dashboard_certification_metadata",
    "load_dashboard_evidence_facts",
    "load_dashboard_replay_facts",
    "load_dashboard_benchmark_facts",
    "load_dashboard_alert_facts",
    "load_dashboard_subsector_facts",
    "load_dashboard_entity_facts",
    "build_dashboard_read_column_inventory",
    "build_dashboard_read_table_inventory",
    "build_dashboard_o7_runtime_report_payload",
    "load_streamlit_dashboard_snapshot",
    "resolve_streamlit_supabase_mode",
    "build_streamlit_supabase_runtime_config",
    "build_dashboard_o8_verification_scope",
    "verify_dashboard_supabase_credentials",
    "verify_dashboard_table_reachability",
    "verify_dashboard_column_contracts",
    "run_dashboard_o8_deployment_smoke_test",
    "build_dashboard_o8_deployment_report_payload",
    "build_dashboard_o9_acceptance_scope",
    "evaluate_dashboard_real_data_presence",
    "evaluate_dashboard_section_population",
    "evaluate_dashboard_degraded_sections",
    "evaluate_dashboard_o8_verification_visibility",
    "run_dashboard_o9_real_data_load_acceptance",
    "build_dashboard_o9_acceptance_report_payload",
    "build_dashboard_o10_closeout_scope",
    "build_dashboard_o10_gate_inventory",
    "run_dashboard_o10_closeout_certification",
    "build_dashboard_o10_closeout_report_payload",
    "build_d1_sample_entities",
    "build_d1_sample_subsectors",
    "build_d1_sample_alerts",
    "build_d1_sample_replay_metadata",
    "build_d1_sample_evidence_chains",
    "build_d1_sample_benchmarks",
    "build_d1_sample_certification_reports",
    "build_d1_seed_payload",
    "build_d1_seed_manifest",
    "run_d1_controlled_seed",
    "build_d1_seed_report_payload",
    "build_d1_guardrail_inventory",
    "build_d1_guardrail_contract",
    "validate_d1_seed_payload_against_guardrails",
    "build_d1_guardrail_manifest",
    "build_d1_guardrail_certification",
    "build_d1_guardrail_report_payload",
    "build_d2_visibility_inventory",
    "build_d2_visibility_requirements",
    "certify_d2_entity_visibility",
    "certify_d2_subsector_visibility",
    "certify_d2_alert_visibility",
    "certify_d2_replay_visibility",
    "certify_d2_evidence_chain_visibility",
    "certify_d2_benchmark_visibility",
    "certify_d2_report_visibility",
    "certify_d2_sample_flag_visibility",
    "certify_d2_empty_degraded_visibility",
    "run_d2_dashboard_visibility_certification",
    "build_d2_visibility_manifest",
    "build_d2_visibility_report_payload",
]


from .dashboard_o2_supabase_contracts import (
    build_dashboard_o2_column_contracts,
    build_dashboard_o2_contract_report,
    build_dashboard_o2_persistence_manifest,
    build_dashboard_o2_table_contracts,
    build_dashboard_o2_unique_key_contracts,
    build_dashboard_o2_upsert_payload,
    validate_dashboard_o2_payload,
)


from .dashboard_o3_supabase_write_adapter import (
    build_dashboard_o3_write_plan,
    validate_dashboard_o3_write_plan,
    execute_dashboard_o3_write_plan,
    build_dashboard_o3_write_result_manifest,
    build_dashboard_o3_dry_run_report,
    build_dashboard_o3_persistence_audit_report,
)

from .dashboard_o4_streamlit_view_model import (
    build_dashboard_o4_view_model,
    build_dashboard_o4_page_registry,
    build_dashboard_o4_filter_options,
    build_dashboard_o4_kpi_cards,
    build_dashboard_o4_entity_table,
    build_dashboard_o4_subsector_table,
    build_dashboard_o4_alert_table,
    build_dashboard_o4_benchmark_table,
    build_dashboard_o4_replay_table,
    build_dashboard_o4_evidence_table,
    build_dashboard_o4_certification_panel,
    validate_dashboard_o4_view_model,
    build_dashboard_o4_ui_manifest,
)


from .dashboard_o5_operationalization_certification import (
    build_dashboard_o5_certification_gates,
    run_dashboard_o5_operationalization_certification,
    build_dashboard_o5_api_inventory,
    build_dashboard_o5_artifact_inventory,
    build_dashboard_o5_boundary_certification,
    build_dashboard_o5_test_coverage_summary,
    build_dashboard_o5_closeout_report,
)


from .dashboard_o6_supabase_read_adapter import (
    build_dashboard_read_table_inventory,
    build_dashboard_read_column_inventory,
    load_dashboard_entity_facts,
    load_dashboard_subsector_facts,
    load_dashboard_alert_facts,
    load_dashboard_benchmark_facts,
    load_dashboard_replay_facts,
    load_dashboard_evidence_facts,
    load_dashboard_certification_metadata,
    build_dashboard_supabase_snapshot,
    build_dashboard_o6_read_adapter_report_payload,
)

from .dashboard_o7_streamlit_supabase_runtime import (
    build_streamlit_supabase_runtime_config,
    resolve_streamlit_supabase_mode,
    load_streamlit_dashboard_snapshot,
    build_dashboard_o7_runtime_report_payload,
)

from .dashboard_o8_supabase_deployment_verification import (
    build_dashboard_o8_verification_scope,
    verify_dashboard_supabase_credentials,
    verify_dashboard_table_reachability,
    verify_dashboard_column_contracts,
    run_dashboard_o8_deployment_smoke_test,
    build_dashboard_o8_deployment_report_payload,
)

from .dashboard_o9_real_data_load_acceptance import (
    build_dashboard_o9_acceptance_scope,
    evaluate_dashboard_real_data_presence,
    evaluate_dashboard_section_population,
    evaluate_dashboard_degraded_sections,
    evaluate_dashboard_o8_verification_visibility,
    run_dashboard_o9_real_data_load_acceptance,
    build_dashboard_o9_acceptance_report_payload,
)

from .dashboard_o10_real_data_operationalization_closeout import (
    build_dashboard_o10_closeout_scope,
    build_dashboard_o10_gate_inventory,
    run_dashboard_o10_closeout_certification,
    build_dashboard_o10_closeout_report_payload,
)


from .dashboard_d1_sample_data_seed import (
    build_d1_sample_entities,
    build_d1_sample_subsectors,
    build_d1_sample_alerts,
    build_d1_sample_replay_metadata,
    build_d1_sample_evidence_chains,
    build_d1_sample_benchmarks,
    build_d1_sample_certification_reports,
    build_d1_seed_payload,
    build_d1_seed_manifest,
    run_d1_controlled_seed,
    build_d1_seed_report_payload,
)


from .dashboard_d1_guardrail_contracts import (
    build_d1_guardrail_inventory,
    build_d1_guardrail_contract,
    validate_d1_seed_payload_against_guardrails,
    build_d1_guardrail_manifest,
    build_d1_guardrail_certification,
    build_d1_guardrail_report_payload,
)

from .dashboard_d2_visibility_certification import (
    build_d2_visibility_inventory,
    build_d2_visibility_requirements,
    certify_d2_entity_visibility,
    certify_d2_subsector_visibility,
    certify_d2_alert_visibility,
    certify_d2_replay_visibility,
    certify_d2_evidence_chain_visibility,
    certify_d2_benchmark_visibility,
    certify_d2_report_visibility,
    certify_d2_sample_flag_visibility,
    certify_d2_empty_degraded_visibility,
    run_d2_dashboard_visibility_certification,
    build_d2_visibility_manifest,
    build_d2_visibility_report_payload,
)
