"""Dashboard operationalization exports for expectation failure subsystem."""

from .dashboard_o1_export_schema import (
    build_dashboard_alert_facts,
    build_dashboard_benchmark_facts,
    build_dashboard_entity_facts,
    build_dashboard_evidence_facts,
    build_dashboard_export_manifest,
    build_dashboard_o1_export_payload,
    build_dashboard_replay_facts,
    build_dashboard_report_metadata,
    build_dashboard_subsector_facts,
)

__all__ = [
    "build_o1_operational_visibility_report",
    "certify_o1_operational_visibility",
    "build_o1_dashboard_view_model",
    "build_o1_governance_boundary_summary",
    "build_o1_replay_lineage_summary",
    "build_o1_operational_status",
    "build_o1_layer_inventory",
    "build_dashboard_entity_facts",
    "build_dashboard_subsector_facts",
    "build_dashboard_alert_facts",
    "build_dashboard_replay_facts",
    "build_dashboard_benchmark_facts",
    "build_dashboard_evidence_facts",
    "build_dashboard_report_metadata",
    "build_dashboard_export_manifest",
    "build_dashboard_o1_export_payload",
    "build_dashboard_o2_table_contracts",
    "build_dashboard_o2_unique_key_contracts",
    "build_dashboard_o2_column_contracts",
    "build_dashboard_o2_upsert_payload",
    "validate_dashboard_o2_payload",
    "build_dashboard_o2_persistence_manifest",
    "build_dashboard_o2_contract_report",
    "build_dashboard_o3_write_plan",
    "validate_dashboard_o3_write_plan",
    "execute_dashboard_o3_write_plan",
    "build_dashboard_o3_write_result_manifest",
    "build_dashboard_o3_dry_run_report",
    "build_dashboard_o3_persistence_audit_report",
    "build_dashboard_o4_view_model",
    "build_dashboard_o4_page_registry",
    "build_dashboard_o4_filter_options",
    "build_dashboard_o4_kpi_cards",
    "build_dashboard_o4_entity_table",
    "build_dashboard_o4_subsector_table",
    "build_dashboard_o4_alert_table",
    "build_dashboard_o4_benchmark_table",
    "build_dashboard_o4_replay_table",
    "build_dashboard_o4_evidence_table",
    "build_dashboard_o4_certification_panel",
    "validate_dashboard_o4_view_model",
    "build_dashboard_o4_ui_manifest",
    "build_dashboard_o5_certification_gates",
    "run_dashboard_o5_operationalization_certification",
    "build_dashboard_o5_api_inventory",
    "build_dashboard_o5_artifact_inventory",
    "build_dashboard_o5_boundary_certification",
    "build_dashboard_o5_test_coverage_summary",
    "build_dashboard_o5_closeout_report",
    "build_dashboard_o6_read_adapter_report_payload",
    "build_dashboard_supabase_snapshot",
    "load_dashboard_certification_metadata",
    "load_dashboard_evidence_facts",
    "load_dashboard_replay_facts",
    "load_dashboard_benchmark_facts",
    "load_dashboard_alert_facts",
    "load_dashboard_subsector_facts",
    "load_dashboard_entity_facts",
    "build_dashboard_read_column_inventory",
    "build_dashboard_read_table_inventory",
    "build_dashboard_o7_runtime_report_payload",
    "build_dashboard_payload_from_supabase_snapshot",
    "load_streamlit_dashboard_snapshot",
    "resolve_streamlit_supabase_mode",
    "build_streamlit_supabase_runtime_config",
    "build_dashboard_o8_verification_scope",
    "verify_dashboard_supabase_credentials",
    "verify_dashboard_table_reachability",
    "verify_dashboard_column_contracts",
    "run_dashboard_o8_deployment_smoke_test",
    "build_dashboard_o8_deployment_report_payload",
    "build_dashboard_expected_table_inventory",
    "build_dashboard_expected_column_inventory",
    "build_dashboard_schema_deployment_manifest",
    "build_dashboard_schema_verification_report_payload",
    "build_dashboard_o9_acceptance_scope",
    "evaluate_dashboard_real_data_presence",
    "evaluate_dashboard_section_population",
    "evaluate_dashboard_degraded_sections",
    "evaluate_dashboard_o8_verification_visibility",
    "run_dashboard_o9_real_data_load_acceptance",
    "build_dashboard_o9_acceptance_report_payload",
    "build_dashboard_o10_closeout_scope",
    "build_dashboard_o10_gate_inventory",
    "run_dashboard_o10_closeout_certification",
    "build_dashboard_o10_closeout_report_payload",
    "build_d1_sample_entities",
    "build_d1_sample_subsectors",
    "build_d1_sample_alerts",
    "build_d1_sample_replay_metadata",
    "build_d1_sample_evidence_chains",
    "build_d1_sample_benchmarks",
    "build_d1_sample_certification_reports",
    "build_d1_seed_payload",
    "build_d1_seed_manifest",
    "run_d1_controlled_seed",
    "build_d1_seed_report_payload",
    "build_d1_guardrail_inventory",
    "build_d1_guardrail_contract",
    "validate_d1_seed_payload_against_guardrails",
    "build_d1_guardrail_manifest",
    "build_d1_guardrail_certification",
    "build_d1_guardrail_report_payload",
    "build_d2_visibility_inventory",
    "build_d2_visibility_requirements",
    "certify_d2_entity_visibility",
    "certify_d2_subsector_visibility",
    "certify_d2_alert_visibility",
    "certify_d2_replay_visibility",
    "certify_d2_evidence_chain_visibility",
    "certify_d2_benchmark_visibility",
    "certify_d2_report_visibility",
    "certify_d2_sample_flag_visibility",
    "certify_d2_empty_degraded_visibility",
    "run_d2_dashboard_visibility_certification",
    "build_d2_visibility_manifest",
    "build_d2_visibility_report_payload",
    "build_d2_dashboard_table_inventory",
    "build_d2_dashboard_column_contract",
    "build_d2_dashboard_index_contract",
    "build_d2_dashboard_constraint_contract",
    "build_d2_dashboard_supabase_schema_contract",
    "certify_d2_dashboard_supabase_schema",
    "build_d2_dashboard_supabase_schema_report",
    "build_d3_playback_inventory",
    "build_d3_supervisor_runbook",
    "build_d3_demo_step_sequence",
    "build_d3_acceptance_gates",
    "build_d3_playback_manifest",
    "build_d3_visibility_walkthrough",
    "build_d3_read_only_boundary_checks",
    "build_d3_degraded_state_walkthrough",
    "build_d3_empty_state_walkthrough",
    "run_d3_supervisor_playback",
    "build_d3_acceptance_payload",
    "build_d3_playback_report_payload",
    "build_d3_persistence_execution_plan",
    "validate_d3_persistence_execution_request",
    "execute_d3_dashboard_persistence",
    "build_d3_persistence_execution_summary",
    "build_d3_persistence_verification_handoff",
    "certify_d3_controlled_dashboard_persistence_execution",
    "build_d3_controlled_dashboard_persistence_execution_report",
    "build_d4_closeout_inventory",
    "build_d4_certification_gates",
    "build_d4_demo_readiness_manifest",
    "certify_d4_operationalization_chain",
    "certify_d4_sample_data_chain",
    "certify_d4_visibility_chain",
    "certify_d4_playback_chain",
    "certify_d4_safety_boundaries",
    "run_d4_demo_environment_closeout",
    "build_d4_closeout_report_payload",
    "build_o2_replay_timeline",
    "build_o2_structural_evolution_summary",
    "build_o2_regime_transition_history",
    "build_o2_pressure_evolution_diagnostics",
    "build_o2_snapshot_comparison_cards",
    "build_o2_replay_certification_cards",
    "build_o2_dashboard_view_model",
    "certify_o2_replay_operationalization",
    "build_o2_replay_operationalization_report",
    "build_o3_real_market_semantic_inputs_report",
    "certify_o3_real_market_semantic_inputs",
    "build_o3_dashboard_view_model",
    "build_o3_semantic_category_summary",
    "build_o3_market_evidence_cards",
    "build_o3_expectation_fragility_inputs",
    "build_o3_semantic_evidence_records",
    "build_o3_market_observation_inventory",
    "build_o4_semantic_dashboard_inventory",
    "build_o4_dashboard_kpi_panels",
    "build_o4_semantic_alert_panels",
    "build_o4_expectation_fragility_sections",
    "build_o4_market_context_sections",
    "build_o4_dashboard_integration_payload",
    "certify_o4_real_market_semantic_dashboard_integration",
    "build_o4_real_market_semantic_dashboard_integration_report",
    "build_o5_finding_inventory",
    "build_o5_semantic_findings",
    "build_o5_dashboard_insight_narratives",
    "build_o5_executive_finding_summary",
    "build_o5_finding_evidence_map",
    "build_o5_supervisor_interpretation_panel",
    "build_o5_finding_generation_payload",
    "certify_o5_semantic_finding_generation",
    "build_o5_semantic_finding_generation_report",
    "build_o6_finding_export_inventory",
    "build_o6_finding_records",
    "build_o6_narrative_records",
    "build_o6_evidence_map_records",
    "build_o6_supervisor_panel_records",
    "build_o6_dashboard_export_bundle",
    "certify_o6_finding_persistence_export_contract",
    "build_o6_finding_persistence_export_contract_report",
    "build_o7_persistence_table_contract",
    "build_o7_write_batch_plan",
    "build_o7_persistence_audit_manifest",
    "validate_o7_persistence_bundle",
    "persist_o7_dashboard_export_bundle",
    "build_o7_persistence_result_summary",
    "certify_o7_dashboard_persistence_adapter",
    "build_o7_dashboard_persistence_adapter_report",
    "build_o8_readback_table_contract",
    "build_d4_real_persistence_readback_verification_report",
    "certify_d4_real_persistence_readback_verification",
    "build_d4_dashboard_verification_handoff",
    "build_d4_readback_execution_summary",
    "verify_d4_dashboard_persistence",
    "execute_d4_dashboard_readback",
    "validate_d4_readback_execution_request",
    "build_d4_readback_execution_plan",
    "build_o9_operationalization_layer_inventory",
    "build_o9_end_to_end_lineage_summary",
    "build_o9_end_to_end_invariant_review",
    "build_o9_governance_boundary_review",
    "build_o9_replay_checksum_manifest",
    "build_o9_dashboard_operationalization_closeout_payload",
    "certify_o9_dashboard_operationalization_closeout",
    "build_o9_dashboard_operationalization_closeout_report",
    "build_d5_execution_layer_inventory",
    "build_d5_real_execution_lineage_summary",
    "build_d5_real_execution_invariant_review",
    "build_d5_schema_persistence_readback_review",
    "build_d5_real_execution_checksum_manifest",
    "build_d6_operational_proving_input",
    "execute_d6_operational_proving_cycle",
    "build_d6_operational_proving_summary",
    "build_d6_operational_proving_report",
    "certify_d6_operational_proving_cycle",
    "build_d5_real_dashboard_execution_closeout_payload",
    "certify_d5_real_dashboard_execution_closeout",
    "build_d5_real_dashboard_execution_closeout_report",
]


from .dashboard_o2_supabase_contracts import (
    build_dashboard_o2_column_contracts,
    build_dashboard_o2_contract_report,
    build_dashboard_o2_persistence_manifest,
    build_dashboard_o2_table_contracts,
    build_dashboard_o2_unique_key_contracts,
    build_dashboard_o2_upsert_payload,
    validate_dashboard_o2_payload,
)


from .dashboard_o3_supabase_write_adapter import (
    build_dashboard_o3_write_plan,
    validate_dashboard_o3_write_plan,
    execute_dashboard_o3_write_plan,
    build_dashboard_o3_write_result_manifest,
    build_dashboard_o3_dry_run_report,
    build_dashboard_o3_persistence_audit_report,
)

from .dashboard_o4_streamlit_view_model import (
    build_dashboard_o4_view_model,
    build_dashboard_o4_page_registry,
    build_dashboard_o4_filter_options,
    build_dashboard_o4_kpi_cards,
    build_dashboard_o4_entity_table,
    build_dashboard_o4_subsector_table,
    build_dashboard_o4_alert_table,
    build_dashboard_o4_benchmark_table,
    build_dashboard_o4_replay_table,
    build_dashboard_o4_evidence_table,
    build_dashboard_o4_certification_panel,
    validate_dashboard_o4_view_model,
    build_dashboard_o4_ui_manifest,
)


from .dashboard_o5_operationalization_certification import (
    build_dashboard_o5_certification_gates,
    run_dashboard_o5_operationalization_certification,
    build_dashboard_o5_api_inventory,
    build_dashboard_o5_artifact_inventory,
    build_dashboard_o5_boundary_certification,
    build_dashboard_o5_test_coverage_summary,
    build_dashboard_o5_closeout_report,
)


from .dashboard_o6_supabase_read_adapter import (
    build_dashboard_read_table_inventory,
    build_dashboard_read_column_inventory,
    load_dashboard_entity_facts,
    load_dashboard_subsector_facts,
    load_dashboard_alert_facts,
    load_dashboard_benchmark_facts,
    load_dashboard_replay_facts,
    load_dashboard_evidence_facts,
    load_dashboard_certification_metadata,
    build_dashboard_supabase_snapshot,
    build_dashboard_o6_read_adapter_report_payload,
)

from .dashboard_o7_streamlit_supabase_runtime import (
    build_streamlit_supabase_runtime_config,
    resolve_streamlit_supabase_mode,
    build_dashboard_payload_from_supabase_snapshot,
    load_streamlit_dashboard_snapshot,
    build_dashboard_o7_runtime_report_payload,
)

from .dashboard_o8_supabase_deployment_verification import (
    build_dashboard_o8_verification_scope,
    verify_dashboard_supabase_credentials,
    verify_dashboard_table_reachability,
    verify_dashboard_column_contracts,
    run_dashboard_o8_deployment_smoke_test,
    build_dashboard_o8_deployment_report_payload,
)

from .o5_semantic_finding_generation import (
    build_o5_finding_inventory,
    build_o5_semantic_findings,
    build_o5_dashboard_insight_narratives,
    build_o5_executive_finding_summary,
    build_o5_finding_evidence_map,
    build_o5_supervisor_interpretation_panel,
    build_o5_finding_generation_payload,
    certify_o5_semantic_finding_generation,
    build_o5_semantic_finding_generation_report,
)

from .dashboard_schema_verification import (
    build_dashboard_expected_table_inventory,
    build_dashboard_expected_column_inventory,
    build_dashboard_schema_deployment_manifest,
    build_dashboard_schema_verification_report_payload,
)

from .dashboard_o9_real_data_load_acceptance import (
    build_dashboard_o9_acceptance_scope,
    evaluate_dashboard_real_data_presence,
    evaluate_dashboard_section_population,
    evaluate_dashboard_degraded_sections,
    evaluate_dashboard_o8_verification_visibility,
    run_dashboard_o9_real_data_load_acceptance,
    build_dashboard_o9_acceptance_report_payload,
)

from .dashboard_o10_real_data_operationalization_closeout import (
    build_dashboard_o10_closeout_scope,
    build_dashboard_o10_gate_inventory,
    run_dashboard_o10_closeout_certification,
    build_dashboard_o10_closeout_report_payload,
)

from .o4_real_market_semantic_dashboard_integration import (
    build_o4_semantic_dashboard_inventory,
    build_o4_dashboard_kpi_panels,
    build_o4_semantic_alert_panels,
    build_o4_expectation_fragility_sections,
    build_o4_market_context_sections,
    build_o4_dashboard_integration_payload,
    certify_o4_real_market_semantic_dashboard_integration,
    build_o4_real_market_semantic_dashboard_integration_report,
)


from .dashboard_d1_sample_data_seed import (
    build_d1_sample_entities,
    build_d1_sample_subsectors,
    build_d1_sample_alerts,
    build_d1_sample_replay_metadata,
    build_d1_sample_evidence_chains,
    build_d1_sample_benchmarks,
    build_d1_sample_certification_reports,
    build_d1_seed_payload,
    build_d1_seed_manifest,
    run_d1_controlled_seed,
    build_d1_seed_report_payload,
)


from .dashboard_d1_guardrail_contracts import (
    build_d1_guardrail_inventory,
    build_d1_guardrail_contract,
    validate_d1_seed_payload_against_guardrails,
    build_d1_guardrail_manifest,
    build_d1_guardrail_certification,
    build_d1_guardrail_report_payload,
)

from .dashboard_d2_visibility_certification import (
    build_d2_visibility_inventory,
    build_d2_visibility_requirements,
    certify_d2_entity_visibility,
    certify_d2_subsector_visibility,
    certify_d2_alert_visibility,
    certify_d2_replay_visibility,
    certify_d2_evidence_chain_visibility,
    certify_d2_benchmark_visibility,
    certify_d2_report_visibility,
    certify_d2_sample_flag_visibility,
    certify_d2_empty_degraded_visibility,
    run_d2_dashboard_visibility_certification,
    build_d2_visibility_manifest,
    build_d2_visibility_report_payload,
)

from .dashboard_d3_supervisor_playback import (
    build_d3_playback_inventory,
    build_d3_supervisor_runbook,
    build_d3_demo_step_sequence,
    build_d3_acceptance_gates,
    build_d3_playback_manifest,
    build_d3_visibility_walkthrough,
    build_d3_read_only_boundary_checks,
    build_d3_degraded_state_walkthrough,
    build_d3_empty_state_walkthrough,
    run_d3_supervisor_playback,
    build_d3_acceptance_payload,
    build_d3_playback_report_payload,
)


from .dashboard_d4_demo_closeout import (
    build_d4_closeout_inventory,
    build_d4_certification_gates,
    build_d4_demo_readiness_manifest,
    certify_d4_operationalization_chain,
    certify_d4_sample_data_chain,
    certify_d4_visibility_chain,
    certify_d4_playback_chain,
    certify_d4_safety_boundaries,
    run_d4_demo_environment_closeout,
    build_d4_closeout_report_payload,
)


from .o1_operational_visibility import (
    build_o1_layer_inventory,
    build_o1_operational_status,
    build_o1_replay_lineage_summary,
    build_o1_governance_boundary_summary,
    build_o1_dashboard_view_model,
    certify_o1_operational_visibility,
    build_o1_operational_visibility_report,
)


from .o2_replay_operationalization import (
    build_o2_replay_timeline,
    build_o2_structural_evolution_summary,
    build_o2_regime_transition_history,
    build_o2_pressure_evolution_diagnostics,
    build_o2_snapshot_comparison_cards,
    build_o2_replay_certification_cards,
    build_o2_dashboard_view_model,
    certify_o2_replay_operationalization,
    build_o2_replay_operationalization_report,
)


from .o3_real_market_semantic_inputs import (
    build_o3_market_observation_inventory,
    build_o3_semantic_evidence_records,
    build_o3_expectation_fragility_inputs,
    build_o3_market_evidence_cards,
    build_o3_semantic_category_summary,
    build_o3_dashboard_view_model,
    certify_o3_real_market_semantic_inputs,
    build_o3_real_market_semantic_inputs_report,
)


from .o6_finding_persistence_export_contract import (
    build_o6_finding_export_inventory,
    build_o6_finding_records,
    build_o6_narrative_records,
    build_o6_evidence_map_records,
    build_o6_supervisor_panel_records,
    build_o6_dashboard_export_bundle,
    certify_o6_finding_persistence_export_contract,
    build_o6_finding_persistence_export_contract_report,
)


from .o7_dashboard_persistence_adapter import (
    build_o7_persistence_table_contract,
    build_o7_write_batch_plan,
    build_o7_persistence_audit_manifest,
    validate_o7_persistence_bundle,
    persist_o7_dashboard_export_bundle,
    build_o7_persistence_result_summary,
    certify_o7_dashboard_persistence_adapter,
    build_o7_dashboard_persistence_adapter_report,
)

from .o8_dashboard_persistence_readback_verification import (
    build_o8_readback_table_contract,
    build_o8_readback_query_plan,
    read_o8_persisted_dashboard_records,
    verify_o8_persisted_dashboard_records,
    build_o8_readback_verification_summary,
    build_o8_persistence_reconciliation_report_payload,
    certify_o8_dashboard_persistence_readback_verification,
    build_o8_dashboard_persistence_readback_verification_report,
)

from .o9_dashboard_operationalization_closeout import (
    build_o9_operationalization_layer_inventory,
    build_o9_end_to_end_lineage_summary,
    build_o9_end_to_end_invariant_review,
    build_o9_governance_boundary_review,
    build_o9_replay_checksum_manifest,
    build_o9_dashboard_operationalization_closeout_payload,
    certify_o9_dashboard_operationalization_closeout,
    build_o9_dashboard_operationalization_closeout_report,
)

from .d2_dashboard_supabase_schema import (
    build_d2_dashboard_table_inventory,
    build_d2_dashboard_column_contract,
    build_d2_dashboard_index_contract,
    build_d2_dashboard_constraint_contract,
    build_d2_dashboard_supabase_schema_contract,
    certify_d2_dashboard_supabase_schema,
    build_d2_dashboard_supabase_schema_report,
)

from .d3_controlled_dashboard_persistence_execution import (
    build_d3_persistence_execution_plan,
    validate_d3_persistence_execution_request,
    execute_d3_dashboard_persistence,
    build_d3_persistence_execution_summary,
    build_d3_persistence_verification_handoff,
    certify_d3_controlled_dashboard_persistence_execution,
    build_d3_controlled_dashboard_persistence_execution_report,
)


from .d4_real_persistence_readback_verification import (
    build_d4_readback_execution_plan,
    validate_d4_readback_execution_request,
    execute_d4_dashboard_readback,
    verify_d4_dashboard_persistence,
    build_d4_readback_execution_summary,
    build_d4_dashboard_verification_handoff,
    certify_d4_real_persistence_readback_verification,
    build_d4_real_persistence_readback_verification_report,
)


from .d5_real_dashboard_execution_closeout import (
    build_d5_execution_layer_inventory,
    build_d5_real_execution_lineage_summary,
    build_d5_real_execution_invariant_review,
    build_d5_schema_persistence_readback_review,
    build_d5_real_execution_checksum_manifest,
    build_d5_real_dashboard_execution_closeout_payload,
    certify_d5_real_dashboard_execution_closeout,
    build_d5_real_dashboard_execution_closeout_report,
)

from .d6_operational_proving_cycle import (
    build_d6_operational_proving_input,
    execute_d6_operational_proving_cycle,
    build_d6_operational_proving_summary,
    build_d6_operational_proving_report,
    certify_d6_operational_proving_cycle,
)
