from __future__ import annotations

SAMPLE_REGISTRY_SOURCES = {
    "fixture_us_listings": [
        {
            "source_url": "file://fixtures/tier3h5_fixture_us_listings.json",
            "issuer_name": "Apple Inc.",
            "country_code": "US",
            "primary_exchange": "NASDAQ",
            "ticker": "AAPL",
            "issuer_type": "operating_company",
            "sec_cik": "0000320193",
            "lei": "HWUPKR0MPOU8FGXBT394",
            "security_name": "Apple Inc. Common Stock",
            "security_type": "equity",
            "currency": "USD",
        },
        {
            "source_url": "file://fixtures/tier3h5_fixture_us_listings.json",
            "issuer_name": "Microsoft Corporation",
            "country_code": "US",
            "primary_exchange": "NASDAQ",
            "ticker": "MSFT",
            "issuer_type": "operating_company",
            "sec_cik": "0000789019",
            "lei": "INR2EJN1ERAN0W5ZP974",
            "security_name": "Microsoft Corporation Common Stock",
            "security_type": "equity",
            "currency": "USD",
        },
        {
            "source_url": "file://fixtures/tier3h5_fixture_us_listings.json",
            "issuer_name": "NVIDIA Corporation",
            "country_code": "US",
            "primary_exchange": "NASDAQ",
            "ticker": "NVDA",
            "issuer_type": "operating_company",
            "sec_cik": "0001045810",
            "lei": "5493009E1C7F2V7O8Y06",
            "security_name": "NVIDIA Corporation Common Stock",
            "security_type": "equity",
            "currency": "USD",
        },
        {
            "source_url": "file://fixtures/tier3h5_fixture_us_listings.json",
            "issuer_name": "Apple Inc.",
            "country_code": "US",
            "primary_exchange": "NASDAQ",
            "ticker": "AAPL",
            "issuer_type": "operating_company",
            "sec_cik": "0000320193",
            "lei": "HWUPKR0MPOU8FGXBT394",
            "security_name": "Apple Inc. Common Stock",
            "security_type": "equity",
            "currency": "USD",
        }
    ],
    "fixture_cross_listing": [
        {
            "source_url": "file://fixtures/tier3h5_fixture_cross_listing.json",
            "issuer_name": "International Business Machines Corporation",
            "country_code": "US",
            "primary_exchange": "NYSE",
            "ticker": "IBM",
            "issuer_type": "operating_company",
            "sec_cik": "0000051143",
            "lei": "5493000K4N0B4D4VQW96",
            "security_name": "IBM Common Stock",
            "security_type": "equity",
            "currency": "USD",
        },
        {
            "source_url": "file://fixtures/tier3h5_fixture_cross_listing.json",
            "issuer_name": "Apple Depositary Receipts",
            "country_code": "US",
            "primary_exchange": "NASDAQ",
            "ticker": "AAPL",
            "issuer_type": "depositary",
            "sec_cik": "0001652044",
            "lei": "213800D1EI4B9WTWWD28",
            "security_name": "Apple Alternate Equity",
            "security_type": "equity",
            "currency": "USD",
        }
    ],
}
