from __future__ import annotations

SAMPLE_STRUCTURED_SOURCE_ROWS = [
    {
        "source_name": "fixture_sec_sample",
        "source_url": "file://fixtures/tier3h5_sec_fixture.json",
        "issuer_name": "Example Holdings Inc.",
        "country_code": "US",
        "primary_exchange": "nasdaq",
        "ticker": " exm ",
        "issuer_type": "operating_company",
        "sec_cik": "0001234567",
        "lei": "5493001KJTIIGC8Y1R12",
        "security_name": "Example Holdings Common Stock",
        "security_type": "common_stock",
        "share_class": "A",
        "currency": "USD",
        "listing_status": "active",
        "is_primary_listing": True,
    },
    {
        "source_name": "fixture_sec_sample",
        "source_url": "file://fixtures/tier3h5_sec_fixture.json",
        "issuer_name": "Example Holdings Inc.",
        "country_code": "US",
        "primary_exchange": "NASDAQ",
        "ticker": "EXM",
        "issuer_type": "operating_company",
        "sec_cik": "0001234567",
        "lei": "5493001KJTIIGC8Y1R12",
        "security_name": "Example Holdings Common Stock",
        "security_type": "common_stock",
        "share_class": "A",
        "currency": "USD",
        "listing_status": "active",
        "is_primary_listing": True,
    },
]
